GET http://localhost:3001/
###
GET http://localhost:3003/api/blogs
###
GET http://localhost:3001/api/blogs/6161f7f0cfd9a78f77be7621
###
DELETE http://localhost:3001/api/blogs/6161f7f0cfd9a78f77be7621
###
POST http://localhost:3001/api/blogs
Content-Type: application/json


{
    "title": "Tester",
    "author": "Ryan Daily",
    "url": "www.mscmoney.com",
    "likes": 83
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvcmVzdHNjaHdydHoiLCJpZCI6IjYxNmI2ODdiYjhjMGM3MzEwNmM3YzdhMSIsImlhdCI6MTYzNDY5Njk0OX0.UcEjKysO8hB5zxkg-Ay9sYoFjpi-A8jVNO2cUvADcXE

{
    "title": "Tester",
    "author": "Ryan Daily",
    "url": "www.mscmoney.com",
    "likes": 83
}
###
GET http://localhost:3003/api/blogs/user
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvcmVzdHNjaHdydHoiLCJpZCI6IjYxNmI2ODdiYjhjMGM3MzEwNmM3YzdhMSIsImlhdCI6MTYzNDkyNzI0OX0.wdjGeeP0p-zzPFAFOWuWDWMFkolfFgL7VcgSGxcs4bs

###
POST http://localhost:3003/api/blogs/6197f1a09854fc946c078b72/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvcmVzdHNjaHdydHoiLCJpZCI6IjYxNmI2ODdiYjhjMGM3MzEwNmM3YzdhMSIsImlhdCI6MTYzNDY5Njk0OX0.UcEjKysO8hB5zxkg-Ay9sYoFjpi-A8jVNO2cUvADcXE

{
    "comment": "great article"
}