GET http://localhost:3001/
###
GET http://localhost:3001/api/patients

###
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "title": "Tester",
    "author": "Ryan Daily",
    "url": "www.mscmoney.com",
    "likes": 83
}
