

GET http://localhost:3003/hello
###
GET http://localhost:3003/bmi?height=180&weight=72
###
POST http://localhost:3003/exercise
Content-Type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}

###
POST http://localhost:3003/exercise
Content-Type: application/json

{
  "daily_exercises": "bob",
  "target": 2.5
}

###
POST http://localhost:3003/exercise
Content-Type: application/json

{
  "target": 2.5
}